[build]
  base = "lotr-site"           # The folder containing your Next.js project
  publish = ".next"    # Or use "next-app/.next" for SSR
  command = "npm run build"   # Your build command, can be "yarn build" too

[[plugins]]
package = "@opennextjs/netlify"
